name: Dependent Task
description: Create a task that depends on the completion of another issue or task
labels: [dependent-task]
body:
  - type: markdown
    attributes:
      value: |
        ## Dependent Task
        Please specify the details of the task and its dependencies.
  - type: input
    id: summary
    attributes:
      label: Task summary
      description: A concise summary of the dependent task.
      placeholder: e.g. Implement feature X after bug Y is fixed
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Task description
      description: Describe the task in detail.
      placeholder: What needs to be done?
    validations:
      required: true
  - type: input
    id: depends-on
    attributes:
      label: Depends on
      description: Reference the issue(s) or task(s) this depends on (e.g., #123, #456).
      placeholder: "#123"
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: What are the requirements for this task to be considered complete?
      placeholder: List clear, testable criteria.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or relevant information.
      placeholder: Any other information?
